### PR TITLE
Add lint + github actions to help with linting

### PR DESCRIPTION
**Pull request by tuliofaria**
@RogerHardiman add this PR to set some lint rules and verifying them using GA. As a progressive adoption, for now, it´s just alerting that we have lint/prettier errors. In the future, we can block a PR from being accepted if this occurs.

### CODE REVIEW

**Comment by RogerHardiman** [comment]
Got family events this weekend so will work through these next week.
If I forget.... send me a reminder nudge on Tuesday.

Thanks for your help, sorry it will be a few days before I merge them in.

**Comment by tuliofaria** [comment]
No problem @RogerHardiman . Take your time :)

**Comment by tuliofaria** [comment]
hey @RogerHardiman :) need any help here ;)

**Comment by RogerHardiman** [comment]
Hi.
I not had time to look at Yellowstone since the summer. The changes look good but the pull request changes lots of files with newline changes (unix to dos newlone changes) which make it hard to see what the new changes actually are.
I'll see if I can undo that change.

**Comment by RogerHardiman** [comment]
I have a question on this change
-const WWW_AUTH_REGEX = new RegExp('([a-zA-Z]+)\s*=\s*"?((?<=").*?(?=")|.*?(?=,?\s*[a-zA-Z]+\s*\=)|.+[^=])', "g");
+const WWW_AUTH_REGEX = new RegExp('([a-zA-Z]+)s*=s*"?((?<=").*?(?=")|.*?(?=,?s*[a-zA-Z]+s*=)|.+[^=])', "g");

We use \s to indicate a whitespace character.
Are you certain that changing it to 's' and not '\s' is still whitespace matching and not just matching the letter 's'

**Comment by RogerHardiman** [comment]
Hi. Just a note to say I've made several changes to Yellowstone to fix some lint errors and fix some async Promises.
So if you are using it in some projects, would you be able to try the latest code from Master please?

Thanks
Roger

**Pull request merged**
