### PR TITLE
Re-write _onData to handle messages and raw data split over packets

### PR DESCRIPTION
**Pull request by RogerHardiman**
As TCP is a stream of data we should not rely on the read from the socket giving us a complete RTSP message. It is perfectly valid for the socket read to give part of a message, with the rest of the message in the next socket read.
It is also perfectly valid for a read from a socket to return the content of several IP packets if they are all in the receive buffer.

(this is different to UDP messaging where we get to process one IP packet at a time)

The previous code would occasionally fall over with the new wowza server when it tried to process the interleaved data but we had not received the 4 header bytes (the $, channel and 2 byte length) from the socket read. This caused the code that read the raw data length to fail.
The old code also falls over with some IP CCTV cameras I have.

This Pull Request re-implements the code that handles the socket reads so that it processes the TCP data byte by byte and the socket read can return any quantity of data from 1 byte to a whole load of IP packets.

Note there is a nice optimisation to make.
When reading the RTSP payload (e.g. the SDP) we know the expected length from Content-Length. When reading the interleaved RTP/RTCP data we also know the length.
So instead of going around the while loop once per byte, Math.Min() and an array copy can be used in a similar way to the old code.

However for now I wanted to share the current code for discussion.

### CODE REVIEW

**Comment by RogerHardiman** [comment]
Many IP cameras stop streaming after 60 seconds unless you send an OPTIONS command as a keep alive (even with RTP over RTSP aka TCP mode).
This code adds a quick check of OPTIONS before implementing a future keepalive timer

**Comment by RogerHardiman** [comment]
While I was at it I also fixed a bug in the RTP header parsing and added code to dump the received H264 data to a .264 file which can be played with ffplay.

**Comment by RogerHardiman** [comment]
Have done a few more commits needed to make yellowstone work with other RTSP servers and IP cameras.
One server sent the Session ID in the format SessionID: 1234;timeout-65
this is valid but we need to strip the timeout when using the SessionID.
Other RTSP servers need a keepalive by sending OPTIONS on a regular basic.
Live555 expects to see regular RTCP Receiver Reports (which I use in the Raspberry PI ONVIF Server project)

So these are all added and yellowstone seems happy receiving H264 video from a number of devices in my office

**Comment by mbullington** [comment]
Hello!

I finally got the time to look through all of your pull requests, again, thank you for the contributions!

If these accomplish the goal of writing to a .264 file, which they seem to, I'm more than happy to merge these pull requests. As I'm just learning how this works myself, my comments might be on a more fundamental level, however there were some things for the consistency of the codebase I'd like to keep.

- Writing to an .264 file seems to have a lot of code in the wowza example, which at times can be extremely confusing (defeating the point of an example). Could you potentially make another class inside the library that handles all of that for you? It wouldn't really be a decoder, so I don't know what you could call it, maybe H264Transport or something similar. And then it would just be an API abstraction over all of the relevant code now in thee wowza example that you could connect to a RtspClient of your choosing.

- Much less relevant than the first one, but I keep seeing a lot of C#-style naming schemes in your pull requests, for example capitalizing constants (Searching vs SEARCHING), and local variable names (camelCase vs camel_case). Having written a decent amount of C# myself, I see where you're coming from, but I'd prefer the codebase to be more consistent in using camelCase for variables, and all capital letters for String or Symbol constants. I can clear this up later on with a better CONTRIBUTING guide, maybe a linter.

Thanks!

**Comment by mbullington** [comment]
Also, if you feel obligated, please feel free to reach out to me directly via email. It seems as since the active contributor base for this library has expanded beyond me, I think as long as we set down some concrete rules such as structure, code style, tests, and versioning, I wouldn't be opposed to giving you direct commit access.

**Comment by RogerHardiman** [comment]
Hi
As I was adding to the wowza example I kept thinking that all this needs go into a set of classes for RTP packet de-packetization somewhere. But decided to finish it off and then discuss it in the Pull Request.

You mentioned the C# naming schemes of lower_case_with_underscores.
In my case it goes back further than C#. I have used lowercase_with_underscore since 1989 (Ada and C). Before that I wrote in BASIC and computers only had 48k of RAM so variable names were short.
Some lint would be great to remind me to use camelCase

**Comment by RogerHardiman** [comment]
H264Transport code and RTCP Empty Receiver Report code moved into base library and out of the wowza example.
When it comes to the Pull, let me know if you want to start with a clean fork without all the revisions.

**Comment by mbullington** [comment]
Hi! I'm sorry I've been inactive on this, I'll need to take a look at everything new on the weekend. :)

**Comment by RogerHardiman** [comment]
No problem.



-------- Original message --------

**Pull request merged**
