### PR TITLE
fixed infinite loop when some auth problem occurs

### PR DESCRIPTION
**Pull request by tuliofaria**

### CODE REVIEW

**Comment by RogerHardiman** [comment]
Hi there
Thanks for the changes.

I've had a few spare minutes this morning to look at the changes but there are lots of linting / formatting changes so I've not found the actual code change yet.

I will try and take a look or @mbullington may review this before me.

Were your linting / formatting fixes applied by VSCode?  or by a standalone linting/formatting tool?
I am just considering applying the linting fixes first as one commit, then apply the actual code changes.

**Comment by RogerHardiman** [comment]
Update - I've found the code change.
```
        responseName: string,
        resHeaders: Headers,
        mediaHeaders: string[]
      ) => {
        const firstAnswer: string = String(resHeaders[""]) || "";
        if (firstAnswer.endsWith("Unauthorized") && id > 2) {
          reject(new Error(`Bad RTSP credentails status code Unauthorized!`));
          return;
        }
        if (resHeaders.CSeq !== id) {



1) Credentials is spelt incorrectly in the error message.
2) We should not be looking for Unauthorized by String Matching. RTSP messages contain error numbers. Unauthorized is error 401 and we should be checking for the Error Number and not an error string.

If you can re-do the commit that would be great.
But if you can split it into a commit with just linting fixes and a commit with the real changes, that would be great.

Thanks
Roger

**Comment by tuliofaria** [comment]
hi @RogerHardiman , I´m going to close this one in favor of #54 .
Later I will open another one for linting. We can even add some github actions for taking care of these things.

For the sake of simplicity, I didnt push the dist folder either.

**Comment by RogerHardiman** [comment]
That sounds wonderful. Many thanks for splitting things up and I do appreciate your fixes.

Roger

**Pull request closed without merging**
