### PR TITLE
Emit the mediaSource from the SDP. Used to extract H264 SPS and PPS

### PR DESCRIPTION
**Pull request by RogerHardiman**
I would like to expand the example to dump the H264 video received from Wowza to a .264 video file which can then be replayed by vlc or ffmpeg (etc)

To implement this we need to extract the SPS and PPS from the SDP and write it to a file (to describe the H264 video data) and then parse the RTP frames to extract the H264 NAL Units and write them to the file.

This is the first step towards this by Emitting the part of the SDP that contains the SPS and PPS

### CODE REVIEW

**Comment by mbullington** [comment]
Hi Roger,

Thanks again for the contribution! I'll be fine with merging this, although, would it be possible to define a mutable variable in the scope of connect(), and then return it in the Promise value rather than an emitted event?

So, instead of client.on('mediaSource', ...), you could just deconstruct the mediaSource object from the response object of connect().

If you have time please address these concerns, if not I'll do this once I get time.

Thanks!

**Comment by RogerHardiman** [comment]
That is a good idea.

Looking to the future it would be good to return the mediaSource for the selected video stream and the selected audio stream.

**Comment by RogerHardiman** [comment]
done

**Comment by mbullington** [comment]
Great, thanks! Merged

**Pull request merged**
